export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_CONFIRM_PASSWORD = 'CHANGE_CONFIRM_PASSWORD';
export const CLEAR_INPUT = 'CLEAR_INPUT';